-- Auto-charge per sale for stores with enabled order fee settings.
-- Designed to be lightweight so sale creation remains fast.

CREATE TABLE IF NOT EXISTS public.store_billing_charges (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id integer NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  sale_id integer NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
  fee_amount numeric(10,2) NOT NULL,
  amount_paid numeric(10,2) NOT NULL DEFAULT 0,
  amount_due numeric(10,2) NOT NULL,
  status character varying(20) NOT NULL DEFAULT 'unpaid',
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT store_billing_charges_sale_unique UNIQUE (sale_id),
  CONSTRAINT store_billing_charges_fee_non_negative CHECK (fee_amount >= 0),
  CONSTRAINT store_billing_charges_amount_paid_non_negative CHECK (amount_paid >= 0),
  CONSTRAINT store_billing_charges_amount_due_non_negative CHECK (amount_due >= 0),
  CONSTRAINT store_billing_charges_status_check CHECK (status IN ('unpaid', 'partial', 'paid', 'waived'))
);

CREATE INDEX IF NOT EXISTS idx_store_billing_charges_store_status
  ON public.store_billing_charges (store_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_store_billing_charges_store_due
  ON public.store_billing_charges (store_id, amount_due);

CREATE OR REPLACE FUNCTION public.update_store_billing_charges_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_store_billing_charges_updated_at ON public.store_billing_charges;
CREATE TRIGGER trg_store_billing_charges_updated_at
BEFORE UPDATE ON public.store_billing_charges
FOR EACH ROW
EXECUTE FUNCTION public.update_store_billing_charges_updated_at();

CREATE OR REPLACE FUNCTION public.create_store_order_fee_charge()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_fee_per_order numeric(10,2);
  v_fee_enabled boolean;
BEGIN
  -- Read fee setting with one indexed lookup.
  SELECT fee_per_order, is_active
  INTO v_fee_per_order, v_fee_enabled
  FROM public.store_order_fee_settings
  WHERE store_id = NEW.store_id
  LIMIT 1;

  -- No fee configured or disabled.
  IF COALESCE(v_fee_enabled, false) = false OR COALESCE(v_fee_per_order, 0) <= 0 THEN
    RETURN NEW;
  END IF;

  -- Idempotent insert in case of retries.
  INSERT INTO public.store_billing_charges (
    store_id,
    sale_id,
    fee_amount,
    amount_paid,
    amount_due,
    status
  ) VALUES (
    NEW.store_id,
    NEW.id,
    v_fee_per_order,
    0,
    v_fee_per_order,
    'unpaid'
  )
  ON CONFLICT (sale_id) DO NOTHING;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_create_store_order_fee_charge ON public.sales;
CREATE TRIGGER trg_create_store_order_fee_charge
AFTER INSERT ON public.sales
FOR EACH ROW
EXECUTE FUNCTION public.create_store_order_fee_charge();

-- Optional backfill so currently existing sales also have charge rows.
INSERT INTO public.store_billing_charges (
  store_id,
  sale_id,
  fee_amount,
  amount_paid,
  amount_due,
  status
)
SELECT
  s.store_id,
  s.id,
  f.fee_per_order,
  0,
  f.fee_per_order,
  'unpaid'
FROM public.sales s
INNER JOIN public.store_order_fee_settings f
  ON f.store_id = s.store_id
WHERE f.is_active = true
  AND COALESCE(f.fee_per_order, 0) > 0
ON CONFLICT (sale_id) DO NOTHING;
