-- Supplier payment history enrichment
ALTER TABLE public.supplier_khaata_payments
  ADD COLUMN IF NOT EXISTS supplier_id integer,
  ADD COLUMN IF NOT EXISTS payment_reference text,
  ADD COLUMN IF NOT EXISTS transaction_remaining_before numeric(10,2),
  ADD COLUMN IF NOT EXISTS transaction_remaining_after numeric(10,2),
  ADD COLUMN IF NOT EXISTS supplier_remaining_before numeric(10,2),
  ADD COLUMN IF NOT EXISTS supplier_remaining_after numeric(10,2);

UPDATE public.supplier_khaata_payments skp
SET supplier_id = sk.supplier_id
FROM public.supplier_khaata sk
WHERE skp.supplier_khaata_id = sk.id
  AND skp.supplier_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_supplier_khaata_payments_supplier_id
  ON public.supplier_khaata_payments (supplier_id, payment_date DESC);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'supplier_khaata_payments_supplier_id_fkey'
  ) THEN
    ALTER TABLE public.supplier_khaata_payments
      ADD CONSTRAINT supplier_khaata_payments_supplier_id_fkey
      FOREIGN KEY (supplier_id)
      REFERENCES public.suppliers(id)
      ON DELETE SET NULL;
  END IF;
END $$;

-- Recurring expense fields on predefined expense templates
ALTER TABLE public.predefined_expenses
  ADD COLUMN IF NOT EXISTS is_recurring boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS recurrence_frequency character varying(20) NOT NULL DEFAULT 'monthly',
  ADD COLUMN IF NOT EXISTS next_due_date date,
  ADD COLUMN IF NOT EXISTS reminder_days_before integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS auto_create boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS default_payment_method character varying(20) NOT NULL DEFAULT 'Cash',
  ADD COLUMN IF NOT EXISTS last_auto_created_on date,
  ADD COLUMN IF NOT EXISTS last_reminded_on date;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'predefined_expenses_recurrence_frequency_check'
  ) THEN
    ALTER TABLE public.predefined_expenses
      ADD CONSTRAINT predefined_expenses_recurrence_frequency_check
      CHECK (recurrence_frequency IN ('daily', 'weekly', 'monthly', 'yearly'));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'predefined_expenses_reminder_days_before_check'
  ) THEN
    ALTER TABLE public.predefined_expenses
      ADD CONSTRAINT predefined_expenses_reminder_days_before_check
      CHECK (reminder_days_before >= 0);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'predefined_expenses_default_payment_method_check'
  ) THEN
    ALTER TABLE public.predefined_expenses
      ADD CONSTRAINT predefined_expenses_default_payment_method_check
      CHECK (default_payment_method IN ('Cash', 'Digital'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_predefined_expenses_recurring_due
  ON public.predefined_expenses (store_id, is_active, is_recurring, next_due_date);

-- Recurring execution / reminder audit
CREATE TABLE IF NOT EXISTS public.recurring_expense_runs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  predefined_expense_id integer NOT NULL,
  store_id integer NOT NULL,
  run_date date NOT NULL,
  due_date date NOT NULL,
  status character varying(30) NOT NULL,
  details text,
  expense_id integer,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT recurring_expense_runs_status_check CHECK (status IN ('auto_created', 'reminder_only', 'skipped', 'failed')),
  CONSTRAINT recurring_expense_runs_predefined_expense_fkey FOREIGN KEY (predefined_expense_id) REFERENCES public.predefined_expenses(id) ON DELETE CASCADE,
  CONSTRAINT recurring_expense_runs_store_fkey FOREIGN KEY (store_id) REFERENCES public.stores(id) ON DELETE CASCADE,
  CONSTRAINT recurring_expense_runs_expense_fkey FOREIGN KEY (expense_id) REFERENCES public.expenses(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_recurring_expense_runs_store_date
  ON public.recurring_expense_runs (store_id, run_date DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_recurring_expense_runs_unique_auto_created
  ON public.recurring_expense_runs (predefined_expense_id, run_date)
  WHERE status = 'auto_created';
