-- Per-store order fee settings managed by super admin.
CREATE TABLE IF NOT EXISTS public.store_order_fee_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id integer NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  fee_per_order numeric(10,2) NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT store_order_fee_settings_fee_non_negative CHECK (fee_per_order >= 0),
  CONSTRAINT store_order_fee_settings_store_unique UNIQUE (store_id)
);

CREATE INDEX IF NOT EXISTS idx_store_order_fee_settings_store
  ON public.store_order_fee_settings (store_id, is_active);

CREATE OR REPLACE FUNCTION public.update_store_order_fee_settings_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_store_order_fee_settings_updated_at ON public.store_order_fee_settings;
CREATE TRIGGER trg_store_order_fee_settings_updated_at
BEFORE UPDATE ON public.store_order_fee_settings
FOR EACH ROW
EXECUTE FUNCTION public.update_store_order_fee_settings_updated_at();
