-- Investors panel base schema (phase 1)
CREATE TABLE IF NOT EXISTS public.investors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id integer NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  investor_name character varying(150) NOT NULL,
  invested_amount numeric(14,2) NOT NULL,
  profit_share_percent numeric(5,2) NOT NULL,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT investors_invested_amount_non_negative CHECK (invested_amount >= 0),
  CONSTRAINT investors_profit_share_range CHECK (profit_share_percent >= 0 AND profit_share_percent <= 100)
);

CREATE INDEX IF NOT EXISTS idx_investors_store_active
  ON public.investors (store_id, is_active, created_at DESC);

CREATE OR REPLACE FUNCTION public.update_investors_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_investors_updated_at ON public.investors;
CREATE TRIGGER trg_investors_updated_at
BEFORE UPDATE ON public.investors
FOR EACH ROW
EXECUTE FUNCTION public.update_investors_updated_at();
